name: Build and Publish

on:
  release:
    types: [created]

  push:
    branches:
      - main
    paths:
      - "pyproject.toml"

jobs:
  pypi:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/l10n_traceback
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v3

      - name: Build package
        run: pdm build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
